#default config value
brokers: "pulsar://192.168.56.101:6650"
messageCount: 10000
timeoutBeforeConsume: 10
maxRedeliveryCount: 5
recordLogOutputEnabled: true
operationTimeoutSeconds: 3
connectTimeoutSeconds: 3

topicName: "persistent://public/namespace-demo/topic-part5-demo"
topicDeadLetterName: "persistent://public/default/topic-output-retry"
