#default config value
brokers: "pulsar://192.168.56.101:6650"
messageCount: 1000
topicInputRouteName: "persistent://public/default/topic-input-route-demo"
topicOutputOrderName: "persistent://public/default/topic-output-order-demo"
topicOutputInvoiceName: "persistent://public/default/topic-output-invoice-demo"
topicInputGroupName: "persistent://public/default/topic-input-group-demo"
topicOutputGroupName: "persistent://public/default/topic-output-demo"
